name: medical_facility_app
description: A Flutter app for managing medical facilities.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2


dependencies:
  uuid: ^4.5.1
  freezed_annotation: ^3.0.0
  riverpod: ^2.6.1
  firebase_dart: ^1.3.6  # instead of firebase_core and firebase_database
  #firebase_core: ^3.13.0
  #firebase_database: ^11.3.0
  dotenv: ^4.2.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  lints: ^5.0.0
  riverpod_test: ^0.1.9
  test: ^1.26.2
  mockito: ^5.4.2
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0